import 'package:flutter/material.dart';
import 'package:remixicon/remixicon.dart';

import '../../../constants/app_color.dart';
import '../../../constants/app_radius.dart';
import '../../../constants/app_spacing.dart';
import '../home_page_model.dart';

/// Home view shown while today's quests are being generated by the backend
/// (async job), or when generation failed / is taking long.
///
/// - [HomeGenerationPhase.generating] → spinner + reassuring copy (no error).
/// - [HomeGenerationPhase.slow] → light "still working, pull to refresh" copy
///   with a retry action.
/// - [HomeGenerationPhase.failed] → error copy with a retry action.
class HomeGenerationView extends StatelessWidget {
  final HomeGenerationPhase phase;
  final String? message;
  final Future<void> Function()? onRetry;

  const HomeGenerationView({
    super.key,
    required this.phase,
    this.message,
    this.onRetry,
  });

  bool get _isGenerating => phase == HomeGenerationPhase.generating;
  bool get _isFailed => phase == HomeGenerationPhase.failed;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(AppSpacing.s32),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            _buildIndicator(),
            const SizedBox(height: AppSpacing.s20),
            Text(
              _title,
              style: const TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.w700,
                color: AppColor.fg,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: AppSpacing.s8),
            Text(
              message ?? _defaultSubtitle,
              style: const TextStyle(
                fontSize: 14,
                color: AppColor.fgSecondary,
                height: 1.5,
              ),
              textAlign: TextAlign.center,
            ),
            if (_isGenerating) ...[
              const SizedBox(height: AppSpacing.s8),
              const Text(
                'Quá trình này có thể mất một chút thời gian.',
                style: TextStyle(fontSize: 13, color: AppColor.fgMuted),
                textAlign: TextAlign.center,
              ),
            ],
            if (!_isGenerating && onRetry != null) ...[
              const SizedBox(height: AppSpacing.s24),
              _RetryButton(onRetry: onRetry!),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildIndicator() {
    if (_isGenerating) {
      return const SizedBox(
        width: 48,
        height: 48,
        child: CircularProgressIndicator(
          strokeWidth: 3,
          valueColor: AlwaysStoppedAnimation<Color>(AppColor.cyan),
        ),
      );
    }
    return Icon(
      _isFailed ? RemixIcons.error_warning_line : RemixIcons.time_line,
      size: 56,
      color: _isFailed ? AppColor.danger : AppColor.warn,
    );
  }

  String get _title {
    if (_isGenerating) return 'Đang tạo quest hôm nay...';
    if (_isFailed) return 'Tạo quest chưa thành công';
    return 'Quest đang được tạo';
  }

  String get _defaultSubtitle {
    if (_isGenerating) return 'Solo đang cá nhân hóa nhiệm vụ cho bạn.';
    if (_isFailed) return 'Không thể tạo quest hôm nay. Hãy thử lại nhé.';
    return 'Quest vẫn đang được tạo. Bạn có thể kéo để làm mới sau.';
  }
}

class _RetryButton extends StatefulWidget {
  final Future<void> Function() onRetry;
  const _RetryButton({required this.onRetry});

  @override
  State<_RetryButton> createState() => _RetryButtonState();
}

class _RetryButtonState extends State<_RetryButton> {
  bool _busy = false;

  Future<void> _handleTap() async {
    if (_busy) return; // guard double tap
    setState(() => _busy = true);
    try {
      await widget.onRetry();
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: _busy ? null : _handleTap,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
        decoration: BoxDecoration(
          color: _busy ? AppColor.surfaceHover : AppColor.cyan,
          borderRadius: BorderRadius.circular(AppRadius.md),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              RemixIcons.refresh_line,
              size: 16,
              color: _busy ? AppColor.fgSecondary : AppColor.bgDeep,
            ),
            const SizedBox(width: 8),
            Text(
              'Thử lại',
              style: TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w700,
                color: _busy ? AppColor.fgSecondary : AppColor.bgDeep,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
